### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Mattwmaster58** [matthewdfuller/skysavvy-docs#3]
Looks like a great extension, would love to see it on Firefox!

**Comment by matthewdfuller** [comment]
Thanks for the request, and appreciate the feedback! Unfortunately this isn't something I plan to support at this time - the market share simply isn't there for Firefox ([~3.3%](https://gs.statcounter.com/browser-market-share)), and it's a lot of extra work for me to support a second browser when this is just a hobby/side project for me. If anyone builds something similar for Firefox, I'll happily recommend it, however!
