### ISSUE TITLE
Plane and Plane Type filter

### ISSUE THREAD

**Issue by eladyarom** [matthewdfuller/skysavvy-docs#4]
Hello, I saw this mentioned on HN and thought I'd give it a try, and I love it overall!

I'd like to request if possible is adding the ability to filter out specific aircraft.
In my case, I'm looking to eliminate turboprops and the 737 max family of planes. 

I think this would be a very very useful feature for anyone who wants to avoid aircraft for various reasons (in my case, noise and safety concerns, respectively)

**Comment by matthewdfuller** [comment]
Hi @eladyarom - thanks for this feature request! I'm happy to share that version 1.6.0 of SkySavvy is now [available in the web store](https://chromewebstore.google.com/detail/skysavvy-enhance-google-f/kpdeplhmnofpohflebkiigblcpogmdeg), which adds filters for aircraft types:

<img width="1355" alt="Screen Shot 2024-02-11 at 11 22 57 AM" src="https://github.com/matthewdfuller/skysavvy-docs/assets/1226686/901579f3-a199-4d84-840f-5a707ee99b4f">

**Comment by eladyarom** [comment]
Hi, thank you so much for this, it's extremely helpful (I just saw the response).
